name: Symfony + PHP - CI Pipeline

on:
  push:
    branches: [ "develop", "main" ]
  pull_request:
    branches: [ "develop", "main" ]

permissions:
  contents: read

jobs:
  quality-check:
    runs-on: ubuntu-latest
    steps:
      # Setup PHP
      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          tools: composer

      # Checkout the code
      - uses: actions/checkout@v3

      # Cache Composer packages
      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v3
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-

      # Install dependencies
      - name: Install Dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

      # PHP_CodeSniffer
      - name: Run PHP_CodeSniffer
        run: vendor/bin/phpcs --standard=PSR2 src/

      # PHPStan
      - name: Run PHPStan
        run: vendor/bin/phpstan analyze src/

      # PHPMD
      - name: Run PHPMD
        run: vendor/bin/phpmd src/ text cleancode,codesize,controversial,design,naming
